#!/bin/bash

NODE=$1
if [[ -z $NODE ]]; then
    echo "Usage: $0 NODE"
    exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
    echo "kubectl not found"
    exit 1
fi

if ! kubectl get node "$NODE" >/dev/null 2>&1; then
    echo "Error from server (NotFound): nodes "$NODE" not found"
    exit 1
fi

PODS=$(kubectl get pods -o wide -A --field-selector spec.nodeName="$NODE" | awk 'NR>1 {print $2}')

if [[ -z "$PODS" ]]; then
    echo "No pods found on node '$NODE'"
    exit 0
fi

shift # drop $1 e.g node name to capture the rest of the flags only (e.g sort by cpu/mem etc)

kubectl top pods -A "${@}" | grep -Ff <(echo "$PODS")
#<() -> process subssitution - creates a temporary file for the pod names to be stored
#-f -> reads from the temporary file
#-F -> treats as fixed strings, not regexes